// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbypnkiziennhzqbhqtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdieXBua2l6aWVubmh6cWJocXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NTEwNjQsImV4cCI6MjA1NjAyNzA2NH0.wpDrKTO8_h8yUDGoTnnek6p7mPdioci0zo_gAPh52Sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);